---
services:
  web:
    image: nginx:1.25.2-alpine
    hostname: web
    ports:
      - "8181:80"
    working_dir: "/var/www/app"
    volumes:
      - ".:/var/www/app"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    links:
      - php
  php:
    build:
      context: .
    hostname: php
    ports:
      - "9000:9000"
    working_dir: "/var/www/app"
    volumes:
      - ".:/var/www/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
